### ISSUE TITLE
Is it working on LineageOS 16 (Android 9 Pie) ?

### ISSUE THREAD

**Issue by Br31zh** [WeAreFairphone/flashable-zip_microG#12] opened 2019-12-16 16:34 UTC
Hello, I'm using LineageOS 16, and since it's working with LOS15 but not LOS17, do you know if it works on LOS16 ?

Thanks.

**Comment by dllud** [comment] 2019-12-21 20:04
I can confirm that [unifiednlp-minimal_2018-08-17.zip](https://github.com/WeAreFairphone/flashable-zip_microG/releases/download/2018-08-17/unifiednlp-minimal_2018-08-17.zip) does not work on LineageOS 16. I am trying to install it with TWRP. The installation seems to be successful but no files get into `/system/priv-app` neither `/etc/permissions`.

Placing the files there manually (via `adb push`) does work and, after reboot, makes the UnifiedNlp Settings appear in the Location Settings.

Perhaps [update-binary](https://github.com/WeAreFairphone/flashable-zip_microG/blob/master/META-INF/com/google/android/update-binary) needs a fix to correctly work on Android 9?

**Comment by dllud** [comment] 2019-12-22 03:18
@Br31zh Does your device use an A/B system-as-root partition style? If so #14 should fix this for you, perhaps in conjugation with #13.

**Comment by Roboe** [comment] 2019-12-23 00:15
I've prepared a pre-release with @dllud contributions. Could someone test them and report results, please? :pray:

https://github.com/WeAreFairphone/flashable-zip_microG/tree/2019-12-23

Thanks everyone!

**Comment by snm247** [comment] 2019-12-29 17:34
The pre-release works on LineageOS 16. After installation and booting into system UnifiedNLP is available in System Settings.

**Comment by Br31zh** [comment] 2020-01-14 17:03
Sorry for the delay, but I confirm that the 2019-12-23 pre-release is working (at least with unifiednlp-minimal) on LineageOS 16. Thanks!

**Comment by Roboe** [comment] 2020-01-15 12:47
Great! Thank you all for testing. I'll make a release right now.

**Comment by Roboe** [comment] 2020-01-15 13:09
Ok, I released it: [2020-01-15](https://github.com/WeAreFairphone/flashable-zip_microG/releases/tag/2020-01-15). There's just a little thing to improve the description there and finally close this issue.

Could someone tell me if the "Note for UnifiedNLP on Android Oreo" in [2018-08-17](https://github.com/WeAreFairphone/flashable-zip_microG/releases/tag/2018-08-17) is still valid for Pie? I.e. if an icon for UnifiedNlp appears in the app drawer or the user should access its config from Location Settings.

**Comment by dllud** [comment] 2020-01-15 13:36
Thanks for the effort @Roboe .

The interface on Pie is the same as in Oreo: user must access it from the Location Settings.

**Comment by Roboe** [comment] 2020-01-15 13:43
Ok, I'll add that to the release description. Thank you again!

**Closed as completed by Roboe** 2020-01-15 13:43 UTC
Labels: help wanted
